version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Entered the install phase..."
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - npm install
  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on `date`"
      - find production.txt
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - app.js
    - production.txt
    - package.json
    - package-lock.json
    - appspec.yml
    - public/**/*
    - scripts/**/*
    - .ebextensions/**/*
    - node_modules/**/*
  discard-paths: no
